# https://github.com/harmslab/gpmap
language: python
python:
    - 3.6
    - 3.5
name: flowsym-environment
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - hdbscan
  - setuptools
  - click
  - pytest
  - seaborn
  - pip
  - pip:
    - fcsy
    - unidip
script: pytest
